# ╔══════════════════════════════════════════════════════════════╗
# ║  STOA LINUX — Picom                                         ║
# ║  "A simplicidade é a sofisticação suprema."                  ║
# ╚══════════════════════════════════════════════════════════════╝

# ── Backend ──
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;
use-damage = true;

# ── Sombras ──
shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.4;
shadow-color = "#0a0908";

shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'i3-frame'",
    "class_g = 'Dunst'",
    "_GTK_FRAME_EXTENTS@:c"
];

# ── Opacidade ──
inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

focus-exclude = [
    "class_g = 'mpv'",
    "class_g = 'firefox'"
];

# ── Cantos Arredondados ──
corner-radius = 4;
rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

# ── Fade ──
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 5;

# ── Regras ──
wintypes:
{
    tooltip = { fade = true; shadow = false; opacity = 0.92; };
    dock = { shadow = false; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 0.95; shadow = true; };
    dropdown_menu = { opacity = 0.95; shadow = true; };
};
