# ╔══════════════════════════════════════════════════════════════╗
# ║  STOA LINUX — btop                                         ║
# ║  "Conhece-te a ti mesmo." — inscrição em Delfos            ║
# ╚══════════════════════════════════════════════════════════════╝

color_theme = "Default"
theme_background = false
vim_keys = true
rounded_corners = true
update_ms = 2000
shown_boxes = "cpu mem net proc"
proc_sorting = "cpu lazy"
proc_tree = false
proc_per_core = false
cpu_single_graph = false
show_uptime = true
show_battery = true
clock_format = "%H:%M"
