# ╔══════════════════════════════════════════════════════════════╗
# ║  STOA LINUX — mpv                                          ║
# ║  "O espetáculo é efêmero." — Marco Aurélio                 ║
# ╚══════════════════════════════════════════════════════════════╝

# ── Vídeo ──
vo=gpu-next
hwdec=auto-safe
gpu-api=vulkan

# ── Áudio ──
ao=pipewire
volume=80
volume-max=150

# ── OSD ──
osd-font="JetBrains Mono"
osd-font-size=20
osd-color="#d4cfc4"
osd-border-color="#211e19"
osd-border-size=2
osd-bar-align-y=0.95
osd-bar-h=1.5

# ── Legendas ──
sub-font="JetBrains Mono"
sub-font-size=36
sub-color="#d4cfc4"
sub-border-color="#211e19"
sub-border-size=2
sub-shadow-offset=1
sub-shadow-color="#1a1714"

# ── Comportamento ──
save-position-on-quit=yes
keep-open=yes
autofit-larger=90%x90%
cursor-autohide=1000

# ── Screenshot ──
screenshot-format=png
screenshot-directory=~/Imagens
screenshot-template="mpv-%F-%P"
