# ╔══════════════════════════════════════════════════════════════╗
# ║  STOA LINUX — GTK 4.0                                      ║
# ║  "Beauty belongs to character." — Marcus Aurelius            ║
# ╚══════════════════════════════════════════════════════════════╝

[Settings]
gtk-theme-name = Adwaita-dark
gtk-icon-theme-name = Colloid-dark
gtk-cursor-theme-name = Colloid-cursors
gtk-cursor-theme-size = 24
gtk-font-name = EB Garamond 11
gtk-application-prefer-dark-theme = true
